Feature/8
CoffeeMapper/frontend pull request #11
Opened 2024-02-26 15:39 UTC by Artematrr

![image](https://github.com/CoffeeMapper/frontend/assets/98470175/b44091f3-55c6-4614-bbdb-2eb96ff95c1b)

2024-02-26 16:14 UTC, rLukoyanov requested changes

2024-02-26 16:14 UTC, rLukoyanov commented on src/ui/Button/Button.module.css
> +  color: #e6e0e9;
вынести цвета в переменные

2024-02-26 16:14 UTC, rLukoyanov commented on src/ui/Button/Button.module.css
> +  background-color: #38b63d;
вынести цвета в переменные

2024-02-26 16:14 UTC, rLukoyanov commented on src/ui/Button/Button.module.css
> +  background-color: #f0c88dbd;
вынести цвета в переменные

2024-02-26 16:14 UTC, rLukoyanov commented on src/ui/Button/Button.module.css
> +  background-color: #1d1b201f;
вынести цвета в переменные

2024-02-26 16:14 UTC, rLukoyanov commented on src/ui/Button/Button.module.css
> +  border-color: #1d1b201f;
вынести цвета в переменные

2024-02-26 16:14 UTC, rLukoyanov commented on src/ui/Button/Button.module.css
> +.button:focus {
это почему пустое?

2024-02-26 16:14 UTC, rLukoyanov commented on src/ui/Button/Button.module.css
> +  /* outline: none; */
почему пустое?

2024-02-26 16:14 UTC, rLukoyanov commented on src/ui/Button/Button.module.css
> +  font-style: normal;
какое значение по умолчанию?

2024-02-26 16:14 UTC, rLukoyanov commented on src/ui/Button/Button.tsx
> +      className={`${styles.button} ${styles[color]}`}
а если я захочу добавить еще класс?

2024-02-26 16:14 UTC, rLukoyanov commented on src/ui/Button/Button.tsx
> +      <Link className={`${styles.button} ${styles[color]}`} href={href}>
Захочу добавить стили?

2024-02-26 16:14 UTC, rLukoyanov commented on src/ui/Button/Button.module.css
> +  background-color: #000;
Вынести цвета

2024-02-26 16:14 UTC, rLukoyanov commented on src/ui/Button/Button.module.css
> +  line-height: 20px; /* 142.857% */
Зачем ты из фигмы копируешь?? Посмотри значения по умолчанию

2024-02-26 16:14 UTC, rLukoyanov commented on src/ui/Button/Button.tsx
> +// components/Button.tsx
может стоит добавить папку `components` и уже в ней добавить `ui`?

2024-02-26 17:03 UTC, Artematrr commented on src/ui/Button/Button.module.css
> +  line-height: 20px; /* 142.857% */
На вид заметно влияют только стили { family: Roboto; size: 14px; weight: 500; }, может только их применить?

2024-02-26 17:03 UTC, Artematrr commented on src/ui/Button/Button.tsx
> +// components/Button.tsx
![image](https://github.com/CoffeeMapper/frontend/assets/98470175/8773732f-7e1c-4947-a450-10edb8411864)
Я решил оттплкиваться от такой архитектуры

2024-02-26 18:01 UTC, rLukoyanov commented on src/ui/Button/Button.tsx
> +// components/Button.tsx
нахуя?

2024-02-26 18:04 UTC, Artematrr commented on src/ui/Button/Button.tsx
> +// components/Button.tsx
Для организации папок

2024-02-26 20:16 UTC, Artematrr commented
![image](https://github.com/CoffeeMapper/frontend/assets/98470175/5655d42a-abfd-4f0d-916a-2e05cfa0edd3)
@rLukoyanov

2024-02-26 21:54 UTC, rLukoyanov requested changes

2024-02-26 21:54 UTC, rLukoyanov commented on src/ui/Button/Button.module.css
> +  --c-green: #38b63d;
Вынеси цвета в :root артем ). В компонентах не хранят переменные

2024-02-27 06:54 UTC, Artematrr commented
@rLukoyanov

2024-02-28 07:47 UTC, rLukoyanov approved these changes

2024-02-28 07:47 UTC, merged